name: Test hardhat on PR
'on': pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardhat unit test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment
        uses: actions/setup-node@v3
      - name: Test
        run: npx hardhat test